### ISSUE TITLE
Create RC versions

### ISSUE THREAD

**Issue by bruno-lopes** [mathifonseca/grails-version-update#4]
Hi,

We use the concept of release candidate versions here. Imagine we are in version 1.0.0 of the app. It would be very nice to have something like this:

**grails version-update p rc**, which turns to 1.0.0-RC1.

Then I could use:
**grails version-update rc**, which turns to 1.0.0-RC2 and so on.

So the rc command would add the suffix RC1 if it doesn't exist, or it would increase the number after the RC if it already exists.

Thanks in advance.

**Comment by mathifonseca** [comment]
Hi @bruno-lopes, thanks for contacting! I'm glad to see anyone uses this plugin :)

I've already considered adding an increasing RC part for the version. The problem is that each of us has a way of managing release candidates. Coincidentally I use the same as you, RC1, RC2, RCn. However, I've seen people that use it like "RC-1", or "RC.1", or lowercase versions of that. There are even people that don't put a number at all and keep it like "RC". The [semver.org](http://semver.org) site (from which I based all the theory behind the plugin) is not very specific on how labels should be written, although it talks about them [here](http://semver.org/#spec-item-9). They even use a strange notation for their own release candidates, "rc.1", like [this one](http://semver.org/spec/v2.0.0-rc.1.html).

Therefore, I'd prefer to leave the label part to be manually inputted by the user. Because if I take the liberty of choosing a format and it is not the one they prefer, they'd have to edit the version manually, losing all the value the plugin tries to offer.

I released version [1.6.0](https://github.com/mathifonseca/grails-version-update/releases/tag/1.6.0) that has a shortcut for appending "-RC" at the end of your version. I've updated the documentation explaining how to use them. I know it's not what you asked for, but it's something. If you want to have numbered RC, you will have to execute the command like:

```
grails version-update m RC1
```
